-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 12:42:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipocuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipocuenta` (
  `idTipoCuenta` INT(11) NOT NULL,
  PRIMARY KEY (`idTipoCuenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcionUsuario` VARCHAR(45) NOT NULL,
  `contrasenaUsuario` VARCHAR(45) NOT NULL,
  `idTipoCuenta` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  UNIQUE INDEX `descripcionUsuario_UNIQUE` (`descripcionUsuario` ASC),
  INDEX `fk_Usuario_TipoCuenta_idx` (`idTipoCuenta` ASC),
  CONSTRAINT `fk_Usuario_TipoCuenta`
    FOREIGN KEY (`idTipoCuenta`)
    REFERENCES `mydb`.`tipocuenta` (`idTipoCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entidad` (
  `idEntidad` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuarioEntidad` INT(11) NOT NULL,
  PRIMARY KEY (`idEntidad`, `idUsuarioEntidad`),
  UNIQUE INDEX `idEntidad_UNIQUE` (`idEntidad` ASC),
  INDEX `fk_Entidad_Usuario1_idx` (`idUsuarioEntidad` ASC),
  CONSTRAINT `fk_Entidad_Usuario1`
    FOREIGN KEY (`idUsuarioEntidad`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `idPersona` INT(11) NOT NULL AUTO_INCREMENT,
  `nombrePersona` VARCHAR(45) NOT NULL,
  `apellido1Persona` VARCHAR(45) NOT NULL,
  `apellido2Persona` VARCHAR(45) NULL DEFAULT NULL,
  `descripcionEmpresaPersona` VARCHAR(45) NULL DEFAULT NULL,
  `idEntidadPersona` INT(11) NOT NULL,
  PRIMARY KEY (`idPersona`, `idEntidadPersona`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC),
  UNIQUE INDEX `idEntidadPersona_UNIQUE` (`idEntidadPersona` ASC),
  INDEX `fk_Persona_Empresa1_idx` (`descripcionEmpresaPersona` ASC),
  INDEX `fk_Persona_Entidad1_idx` (`idEntidadPersona` ASC),
  CONSTRAINT `fk_Persona_Entidad1`
    FOREIGN KEY (`idEntidadPersona`)
    REFERENCES `mydb`.`entidad` (`idEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`correo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`correo` (
  `idCorreo` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcionCorreo` VARCHAR(45) NOT NULL,
  `idPersonaCorreo` INT(11) NOT NULL,
  PRIMARY KEY (`idCorreo`),
  UNIQUE INDEX `idCorreo_UNIQUE` (`idCorreo` ASC),
  INDEX `fk_Correo_Persona2_idx` (`idPersonaCorreo` ASC),
  CONSTRAINT `fk_Correo_Persona2`
    FOREIGN KEY (`idPersonaCorreo`)
    REFERENCES `mydb`.`persona` (`idPersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direccion` (
  `idDireccion` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcionDireccion` VARCHAR(1000) NOT NULL,
  `idEntidadDireccion` INT(11) NOT NULL,
  PRIMARY KEY (`idDireccion`, `idEntidadDireccion`),
  UNIQUE INDEX `idDireccion_UNIQUE` (`idDireccion` ASC),
  INDEX `fk_Direccion_Entidad1_idx` (`idEntidadDireccion` ASC),
  CONSTRAINT `fk_Direccion_Entidad1`
    FOREIGN KEY (`idEntidadDireccion`)
    REFERENCES `mydb`.`entidad` (`idEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `idEmpresa` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcionEmpresa` VARCHAR(45) NOT NULL,
  `idEntidadEmpresa` INT(11) NOT NULL,
  PRIMARY KEY (`idEmpresa`, `idEntidadEmpresa`),
  UNIQUE INDEX `idEmpresa_UNIQUE` (`idEmpresa` ASC),
  UNIQUE INDEX `idEntidadEmpresa_UNIQUE` (`idEntidadEmpresa` ASC),
  INDEX `fk_Empresa_Entidad1_idx` (`idEntidadEmpresa` ASC),
  CONSTRAINT `fk_Empresa_Entidad1`
    FOREIGN KEY (`idEntidadEmpresa`)
    REFERENCES `mydb`.`entidad` (`idEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `precio` INT(200) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`propuestaventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`propuestaventa` (
  `idPropuestaVenta` INT(11) NOT NULL AUTO_INCREMENT,
  `productoPropuestaVenta` INT(45) NOT NULL,
  `fechaPropuestaVenta` DATE NOT NULL,
  `precio` INT(11) NOT NULL,
  `idVendedor` INT(11) NOT NULL,
  `idContacto` INT(11) NOT NULL,
  PRIMARY KEY (`idPropuestaVenta`),
  INDEX `productoPropuestaVenta` (`productoPropuestaVenta` ASC),
  INDEX `idVendedor` (`idVendedor` ASC),
  INDEX `idContacto` (`idContacto` ASC),
  CONSTRAINT `fkProductoPropuestaVenta`
    FOREIGN KEY (`productoPropuestaVenta`)
    REFERENCES `mydb`.`producto` (`idProducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkVendedor`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `propuestaventa_ibfk_1`
    FOREIGN KEY (`idContacto`)
    REFERENCES `mydb`.`entidad` (`idEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reporte` (
  `idReporte` INT(11) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `FechaReporte` DATE NOT NULL,
  `idProducto` INT(11) NOT NULL,
  `idCliente` INT(11) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReporte`),
  INDEX `fk_Reporte_Producto_idx` (`idProducto` ASC),
  INDEX `fk_Reporte_Usuario_idx` (`idCliente` ASC),
  CONSTRAINT `fk_Reporte_Producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Usuario`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`respuestadepropuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuestadepropuesta` (
  `idRespuestaDePropuesta` INT(11) NOT NULL AUTO_INCREMENT,
  `idPropuestaVenta` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `respuesta` VARCHAR(200) NOT NULL DEFAULT 'No especificada.',
  `estado` VARCHAR(200) NOT NULL DEFAULT 'Sin respuesta.',
  PRIMARY KEY (`idRespuestaDePropuesta`),
  INDEX `idPropuestaVenta` (`idPropuestaVenta` ASC),
  CONSTRAINT `fkPropuestaVenta`
    FOREIGN KEY (`idPropuestaVenta`)
    REFERENCES `mydb`.`propuestaventa` (`idPropuestaVenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefono` (
  `idTelefono` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcionTelefono` VARCHAR(45) NOT NULL,
  `idEntidadTelefono` INT(11) NOT NULL,
  PRIMARY KEY (`idTelefono`),
  UNIQUE INDEX `idTelefono_UNIQUE` (`idTelefono` ASC),
  INDEX `fk_Telefono_Entidad1_idx` (`idEntidadTelefono` ASC),
  CONSTRAINT `fk_Telefono_Entidad1`
    FOREIGN KEY (`idEntidadTelefono`)
    REFERENCES `mydb`.`entidad` (`idEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `idVenta` INT(11) NOT NULL AUTO_INCREMENT,
  `idProducto` INT(11) NOT NULL,
  `descuento` INT(11) NOT NULL,
  `porcentajeComision` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `precioFinal` INT(11) NOT NULL,
  `comision` INT(11) NOT NULL,
  `idVendedor` INT(11) NOT NULL,
  `idContacto` INT(11) NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `idProducto` (`idProducto` ASC),
  INDEX `idVendedor` (`idVendedor` ASC),
  INDEX `idContacto` (`idContacto` ASC),
  CONSTRAINT `fkIdContacto`
    FOREIGN KEY (`idContacto`)
    REFERENCES `mydb`.`entidad` (`idEntidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `vendedor_ibfk_1`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `venta_ibfk_1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`producto` (`idProducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
